# Generated by Django 5.2.4 on 2025-12-06 14:04

import core.base.models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CSVMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("amount", models.CharField(blank=True, max_length=128, null=True)),
                ("header", models.IntegerField(blank=True, default=0, null=True)),
                ("my_note", models.CharField(blank=True, max_length=128, null=True)),
                ("currency", models.CharField(blank=True, max_length=128, null=True)),
                ("encoding", models.CharField(default="utf-8", max_length=128)),
                ("delimiter", models.CharField(default=",", max_length=5)),
                (
                    "other_note",
                    models.TextField(
                        blank=True,
                        help_text="Store a list of notes as a comma-separated string.",
                        null=True,
                    ),
                ),
                (
                    "original_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "constant_symbol",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "specific_symbol",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "variable_symbol",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "transaction_type",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "counterparty_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "counterparty_note",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "date_of_submission_value",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "date_of_submission_format",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("date_of_transaction_value", models.CharField(max_length=128)),
                (
                    "date_of_transaction_format",
                    models.CharField(default="%d.%m.%Y", max_length=128),
                ),
                (
                    "counterparty_account_number",
                    models.CharField(
                        blank=True,
                        help_text="Can be account number with or without bank code.",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "counterparty_bank_code",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "categorization_fields",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("my_note", "My Note"),
                            ("other_note", "Other Note"),
                            ("counterparty_note", "Counterparty Note"),
                            ("counterparty_name", "Counterparty Name"),
                            (
                                "counterparty_account_number",
                                "Counterparty Account Number",
                            ),
                            ("transaction_type", "Transaction Type"),
                            ("variable_symbol", "Variable Symbol"),
                            ("specific_symbol", "Specific Symbol"),
                            ("constant_symbol", "Constant Symbol"),
                        ],
                        help_text="Select fields you want to use for categorization.",
                        max_length=147,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_number", models.CharField(max_length=128)),
                ("account_name", models.CharField(max_length=128)),
                ("owners", models.IntegerField(default=1)),
                (
                    "csv_mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_accounts",
                        to="base.csvmapping",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.category"
                    ),
                ),
            ],
            options={
                "ordering": ["category__name", "name"],
                "unique_together": {("name", "category")},
            },
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "rules",
                    models.JSONField(
                        blank=True,
                        default=core.base.models.get_default_keyword_rules,
                        max_length=128,
                    ),
                ),
                (
                    "want_need_investment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("want", "Want"),
                            ("investment", "Investment"),
                            ("need", "Need"),
                            ("other", "Other"),
                        ],
                        max_length=128,
                        null=True,
                    ),
                ),
                ("ignore", models.BooleanField(default=False)),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.subcategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("date_of_submission", models.DateTimeField(blank=True, null=True)),
                ("date_of_transaction", models.DateTimeField()),
                (
                    "counterparty_account_number",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "counterparty_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "transaction_type",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "variable_symbol",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "specific_symbol",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "constant_symbol",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("counterparty_note", models.TextField(blank=True, null=True)),
                ("my_note", models.TextField(blank=True, null=True)),
                ("other_note", models.TextField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=3)),
                (
                    "want_need_investment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("want", "Want"),
                            ("investment", "Investment"),
                            ("need", "Need"),
                            ("other", "Other"),
                        ],
                        max_length=128,
                        null=True,
                    ),
                ),
                ("ignore", models.BooleanField(default=False)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.bankaccount",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.subcategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.tag"
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.transaction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
