# Generated by Django 5.0.2 on 2024-11-09 12:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_number", models.CharField(max_length=128)),
                ("bank_code", models.CharField(blank=True, max_length=128, null=True)),
                ("account_name", models.CharField(max_length=128)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_of_submission", models.DateTimeField(blank=True, null=True)),
                ("date_of_transaction", models.DateTimeField()),
                (
                    "counterparty_account_number",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "counterparty_bank_code",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "counterparty_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "transaction_type",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "variable_symbol",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "specific_symbol",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "constant_symbol",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("counterparty_note", models.TextField(blank=True, null=True)),
                ("my_note", models.TextField(blank=True, null=True)),
                ("other_note", models.TextField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=3)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.category"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
