# Generated by Django 5.0.2 on 2024-11-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_keyword_wni"),
    ]

    operations = [
        migrations.RenameField(
            model_name="keyword",
            old_name="wni",
            new_name="want_need_investment",
        ),
    ]
