# Generated by Django 5.0.2 on 2024-12-27 19:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_rename_wni_keyword_want_need_investment"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSVMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("mapping_json", models.JSONField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
