# Generated by Django 5.0.2 on 2024-12-31 08:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_remove_transaction_counterparty_bank_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccount",
            name="bank_code",
        ),
    ]
