# Generated by Django 5.0.2 on 2025-01-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_csvmapping_amount_csvmapping_bank_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="csvmapping",
            name="currency",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
