# Generated by Django 5.0.2 on 2025-01-05 10:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0012_alter_csvmapping_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="csvmapping",
            name="bank_account",
        ),
        migrations.RemoveField(
            model_name="csvmapping",
            name="mapping_json",
        ),
    ]
