# Generated by Django 5.0.2 on 2025-01-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_remove_csvmapping_bank_account_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={"ordering": ["category__name", "name"]},
        ),
        migrations.AlterField(
            model_name="keyword",
            name="value",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
