# Generated by Django 5.0.2 on 2025-01-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_keyword_ignore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcategory",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
