# Generated by Django 5.0.2 on 2025-03-15 13:54

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0016_alter_subcategory_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvmapping",
            name="categorization_fields",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("counterparty_note", "Counterparty Note"),
                    ("counterparty_name", "Counterparty Name"),
                    ("transaction_type", "Transaction Type"),
                ],
                max_length=52,
            ),
        ),
    ]
