# Generated by Django 5.0.2 on 2025-03-23 06:54

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0017_csvmapping_categorization_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="csvmapping",
            name="categorization_fields",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("my_note", "My Note"),
                    ("other_note", "Other Note"),
                    ("counterparty_note", "Counterparty Note"),
                    ("counterparty_name", "Counterparty Name"),
                    ("transaction_type", "Transaction Type"),
                    ("variable_symbol", "Variable Symbol"),
                    ("specific_symbol", "Specific Symbol"),
                    ("constant_symbol", "Constant Symbol"),
                ],
                help_text="Select fields you want to use for categorization.",
                max_length=119,
            ),
        ),
        migrations.CreateModel(
            name="CurrencyConversionRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_od_conversion", models.DateField()),
                ("currency", models.CharField(max_length=3)),
                (
                    "conversion_rate_to_eur",
                    models.DecimalField(decimal_places=6, max_digits=12),
                ),
            ],
            options={
                "unique_together": {("date_od_conversion", "currency")},
            },
        ),
    ]
