# Generated by Django 5.0.2 on 2025-07-07 20:32

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0018_alter_csvmapping_categorization_fields_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CurrencyConversionRate",
        ),
        migrations.AlterField(
            model_name="csvmapping",
            name="categorization_fields",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("my_note", "My Note"),
                    ("other_note", "Other Note"),
                    ("counterparty_note", "Counterparty Note"),
                    ("counterparty_name", "Counterparty Name"),
                    (
                        "counterparty_account_numbertransaction_type",
                        "Counterparty Account Numbertransaction Type",
                    ),
                    ("variable_symbol", "Variable Symbol"),
                    ("specific_symbol", "Specific Symbol"),
                    ("constant_symbol", "Constant Symbol"),
                ],
                help_text="Select fields you want to use for categorization.",
                max_length=146,
            ),
        ),
    ]
