# Generated by Django 5.0.2 on 2025-07-13 09:59

import core.base.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0020_keyword_rules_alter_csvmapping_categorization_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyword",
            name="rules",
            field=models.JSONField(
                blank=True,
                default=core.base.models.get_default_keyword_rules,
                max_length=128,
            ),
        ),
    ]
