# Generated by Django 5.2.4 on 2025-11-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_keyword_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='value',
        ),
        migrations.AddField(
            model_name='keyword',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
