# Generated by Django 5.2.4 on 2025-11-29 13:34

from django.db import migrations


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0022_remove_keyword_value_keyword_description"),
    ]

    operations = []
