# Generated by Django 5.2.4 on 2025-11-30 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0023_auto_20251129_1334"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.subcategory",
            ),
        ),
    ]
