# Generated by Django 5.2.4 on 2025-12-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0025_alter_transaction_bank_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
