# Generated by Django 5.2.4 on 2025-12-05 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0026_alter_category_name_alter_tag_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subcategory",
            unique_together={("name", "category")},
        ),
    ]
