# Generated by Django 5.2.4 on 2025-12-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0027_alter_subcategory_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="raw_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
