# Generated by Django 5.2.4 on 2025-12-06 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0028_transaction_raw_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="csv_mapping",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_accounts",
                to="base.csvmapping",
            ),
        ),
    ]
